test with prebuilt on and now windows

diff --git a/.github/workflows/github_actions.yml b/.github/workflows/github_actions.yml
--- a/.github/workflows/github_actions.yml
+++ b/.github/workflows/github_actions.yml
@@ -14,24 +14,24 @@ jobs:
     steps:
       - name: checkout
         uses: actions/checkout@v2
-
-      - name: checkFormat
-        uses: gradle/gradle-build-action@v1
-        with:
-          arguments: checkFormat
-
-      - name: assemble
-        uses: gradle/gradle-build-action@v1
-        with:
-          arguments: assemble
-
-      - name: test
-        uses: gradle/gradle-build-action@v1
-        with:
-          arguments: test
-    env:
-      ORG_GRADLE_PROJECT_TILEDB_SERIALIZATION: OFF
-      ORG_GRADLE_PROJECT_TILEDB_S3: OFF
+#
+#      - name: checkFormat
+#        uses: gradle/gradle-build-action@v1
+#        with:
+#          arguments: checkFormat
+#
+#      - name: assemble
+#        uses: gradle/gradle-build-action@v1
+#        with:
+#          arguments: assemble
+#
+#      - name: test
+#        uses: gradle/gradle-build-action@v1
+#        with:
+#          arguments: test
+#    env:
+#      ORG_GRADLE_PROJECT_TILEDB_SERIALIZATION: OFF
+#      ORG_GRADLE_PROJECT_TILEDB_S3: OFF
 
 
   Test_Ubuntu_macOS:
@@ -89,44 +89,44 @@ jobs:
     steps:
       - name: checkout
         uses: actions/checkout@v2
-
-      - run: |
-          mkdir binaries_Windows
-          ./gradlew.bat assemble
-          Copy-Item ./build/tiledb_jni/Release/*.dll -Destination ./binaries_Windows/
-          Copy-Item ./build/install/bin/*.dll -Destination ./binaries_Windows/
-        name: Assemble
-
-      - run: |
-          set -e pipefail
-          # Display log files if the build failed
-          echo "Dumping log files for failed build"
-          echo "----------------------------------"
-          for f in $(find $BUILD_REPOSITORY_LOCALPATH -name *.log);
-            do echo "------"
-               echo $f
-               echo "======"
-               cat $f
-            done;
-        if: ${{ failure() }}
-        name: "Print log files (failed build only)"
-
-      - name: Archive files
-        uses: master-atul/tar-action@v1.0.2
-        id: compress
-        with:
-          command: c
-          cwd: ./
-          files: |
-            ./binaries_Windows
-          outPath: tiledb-Win.gz.tar
-
-      - uses: actions/upload-artifact@v2
-        with:
-          name: Upload-Artifact-Windows
-          path: tiledb-Win.gz.tar
-    env:
-      ORG_GRADLE_PROJECT_TILEDB_S3: ON
+#
+#      - run: |
+#          mkdir binaries_Windows
+#          ./gradlew.bat assemble
+#          Copy-Item ./build/tiledb_jni/Release/*.dll -Destination ./binaries_Windows/
+#          Copy-Item ./build/install/bin/*.dll -Destination ./binaries_Windows/
+#        name: Assemble
+#
+#      - run: |
+#          set -e pipefail
+#          # Display log files if the build failed
+#          echo "Dumping log files for failed build"
+#          echo "----------------------------------"
+#          for f in $(find $BUILD_REPOSITORY_LOCALPATH -name *.log);
+#            do echo "------"
+#               echo $f
+#               echo "======"
+#               cat $f
+#            done;
+#        if: ${{ failure() }}
+#        name: "Print log files (failed build only)"
+#
+#      - name: Archive files
+#        uses: master-atul/tar-action@v1.0.2
+#        id: compress
+#        with:
+#          command: c
+#          cwd: ./
+#          files: |
+#            ./binaries_Windows
+#          outPath: tiledb-Win.gz.tar
+#
+#      - uses: actions/upload-artifact@v2
+#        with:
+#          name: Upload-Artifact-Windows
+#          path: tiledb-Win.gz.tar
+#    env:
+#      ORG_GRADLE_PROJECT_TILEDB_S3: ON
 
   Create_Artifacts_Ubuntu_MacOS:
     if: startsWith(github.ref, 'refs/tags/')
@@ -240,9 +240,9 @@ jobs:
           mv libtiledbjni.so ./build/tiledb_jni
 
           # Windows
-          mv tbb.dll ./build/install/bin
-          mv tiledb.dll ./build/install/bin
-          mv tiledbjni.dll ./build/tiledb_jni/Release
+          #mv tbb.dll ./build/install/bin
+          #mv tiledb.dll ./build/install/bin
+          #mv tiledbjni.dll ./build/tiledb_jni/Release
 
           ./gradlew assemble
 
